"""Iterative intelligence contracts — Iteration 09.

Defines the typed contract surface for adaptive re-query directives and
budget-aware session tracking. The full adaptive LLM loop and contradiction-
targeting behavior are explicitly out of scope here (moved to a future
intelligence-upgrades program).

Canonical usage
---------------
1. A ``LiteratureQueryFacadeService`` running with ``iteration_budget > 1``
   emits one ``IterativeIntelligenceDirective`` per iteration.
2. All directives for a single user request accumulate inside an
   ``IterativeLiteratureSession``.
3. When ``should_continue is False`` or the budget is exhausted, the session
   reaches ``final_verdict`` and the facade returns.

Not in scope (future program)
------------------------------
- Production LLM-driven re-query
- Real contradiction detector
- Quality-score models
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class IterativeIntelligenceDirective(BaseModel):
    """Output of one iteration in an adaptive literature acquisition loop.

    Emitted by ``LiteratureQueryFacadeService`` at the end of each iteration
    (including the first). When ``iteration_budget == 1`` (default), exactly
    one directive is emitted with ``should_continue = False``.

    Fields
    ------
    re_query_terms
        Additional search terms to inject into the next iteration.  Empty list
        if no refinement is warranted.
    budget_remaining_usd
        Remaining monetary budget after this iteration completes.  Starts at
        ``acquisition_budget_usd`` from the facade request and decrements by
        the amount spent in each iteration.  ``None`` when no budget cap was
        requested.
    contradictions_found
        Human-readable contradiction notes identified in this iteration's
        result set.  Empty list when no contradictions were found.  Populated
        by stub skeleton in the absence of a real detector.
    quality_score
        Estimated quality of the acquired corpus in ``[0.0, 1.0]``.  0.0 in
        stub mode.
    should_continue
        ``True`` if another iteration is warranted.  The facade service sets
        this to ``False`` when the budget is exhausted or the iteration budget
        cap is reached.
    """

    re_query_terms: List[str] = Field(
        default_factory=list,
        description="Additional search terms for the next iteration. Empty if no refinement needed.",
    )
    budget_remaining_usd: Optional[float] = Field(
        None,
        ge=0.0,
        description="Remaining acquisition budget after this iteration. None if no budget cap.",
    )
    contradictions_found: List[str] = Field(
        default_factory=list,
        description="Contradiction notes from this iteration. Stub: always empty.",
    )
    quality_score: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Estimated corpus quality in [0, 1]. Stub: always 0.0.",
    )
    should_continue: bool = Field(
        False,
        description="True if another iteration is warranted given budget and quality signal.",
    )


class IterativeLiteratureSession(BaseModel):
    """Container for all directives emitted during one adaptive acquisition run.

    Created by ``LiteratureQueryFacadeService`` when ``iteration_budget > 1``.
    When ``iteration_budget == 1`` (default) the session still exists but holds
    exactly one directive with ``should_continue = False``.

    The ``final_verdict`` field is set by the service after the loop closes.

    Fields
    ------
    session_id
        Identifier tied to ``LiteratureQueryFacadeRequest.session_id`` (or
        auto-generated by the service when none was provided).
    directives
        Ordered list of directives, one per iteration.
    iteration_count
        Total number of iterations that ran.  Always ``len(directives)``.
    final_verdict
        Human-readable closure summary.  ``"budget_exhausted"``,
        ``"max_iterations_reached"``, or ``"quality_threshold_met"`` are the
        canonical values for stub mode.  ``None`` while the session is still
        open.
    """

    session_id: str = ""
    directives: List[IterativeIntelligenceDirective] = Field(default_factory=list)
    iteration_count: int = Field(0, ge=0)
    final_verdict: Optional[str] = None

    def append_directive(self, directive: IterativeIntelligenceDirective) -> None:
        """Append a directive and keep ``iteration_count`` in sync."""
        self.directives.append(directive)
        self.iteration_count = len(self.directives)

    def is_open(self) -> bool:
        """Return ``True`` if the session has no final verdict yet."""
        return self.final_verdict is None
